require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

def share_pods 
  pod 'react-native-config', :path => '../node_modules/react-native-config'
end

target 'ReactNativeCklExample' do
  share_pods
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Enables Flipper.
  # use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  use_flipper!()
  # use_flipper!({"Flipper-DoubleConversion" => "1.1.7" })

end

target 'ReactNativeCklExampleDevelop' do
  share_pods
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )
  use_flipper!()
end

target 'ReactNativeCklExampleStaging' do
  share_pods
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )
  use_flipper!()
  
end

post_install do |installer|
  react_native_post_install(installer)
end